package App.Commands.Challenge1.Solution;

import App.Commands.DefinedCmd.DefinedCmd;
import App.MemorySpace;
import App.Pointer;
import App.Store;

/**
 * solution generated by BruceFindSolution class
 */
public class Sol13Cmd extends DefinedCmd {

    public Sol13Cmd(Pointer pointer, MemorySpace memorySpace, Store store) {
        super(pointer, memorySpace, store);
    }

    /**
     * LOAD
     * INC
     * INV
     * CDEC
     * INV
     * LOAD
     * CDEC
     * INC
     * LOAD
     * CDEC
     * INC
     * INC
     * INV
     */
    @Override
    protected void loadCommands() {
        cmdList.add(cmdHelper.getCmdLOAD());
        cmdList.add(cmdHelper.getCmdINC());
        cmdList.add(cmdHelper.getCmdINV());
        cmdList.add(cmdHelper.getCmdCDEC());
        cmdList.add(cmdHelper.getCmdINV());
        cmdList.add(cmdHelper.getCmdLOAD());
        cmdList.add(cmdHelper.getCmdCDEC());
        cmdList.add(cmdHelper.getCmdINC());
        cmdList.add(cmdHelper.getCmdLOAD());
        cmdList.add(cmdHelper.getCmdCDEC());
        cmdList.add(cmdHelper.getCmdINC());
        cmdList.add(cmdHelper.getCmdINC());
        cmdList.add(cmdHelper.getCmdINV());
    }
}
